### ISSUE TITLE
Volume Flyout

### ISSUE THREAD

**Issue by mihajlo001** [SB0519/WIndow-11-AME#1]
I managed to fix the battery and network flyout with the Winaero tweaker, but i cannot fix the volume flyout in the bottom right corner. Do you have a solution to that?

**Comment by SB0519** [comment]
I was able to fix it with startisback. I believe I put the instructions in
the readme. This will also work with 22H2 and the flyout works on that
however you still need startisback to fix the calendar. The current script
still works but I need to update it to fix some minor bugs in current
script.

**Comment by mihajlo001** [comment]
Thanks. I installed 22h2 today and it was working with Startallback. But i found some really cool program. Its called Classic volume control. Thanks again, the script is amazing

**Comment by SB0519** [comment]
Thanks for giving this a try I hope many others get some good use out of this. I will say that this script does remove a lot if not all the telemetry but there maybe some more baked into the OS but I tried to add as much IP's that I have detected to the host file to block and I believe I found 2 more and added it to the latest script but haven't uploaded it yet. If you do find anything in cmd netstat -t search the IP that shows established and if it saids Microsoft, Azure, or bing add it to windows/drivers/etc/host in linux and please let me know here. I would also recommend disabling IPV6 as its not really needed on a home network and will allow you to keep track of what your pc connects to.

**Comment by mihajlo001** [comment]
Oh wow didn't even know about this stuff, learning everyday. Okay, there were 10-15 addresses and I don't know if I understood correctly but I just Googled those Foreign Addresses
 like: 
cdn-185-199-111-153:https
bud02s35-in-f4:https

 and it was showing github and google mostly, none of them pointed to MS,azure,bing... If i find some ill let you know. Thanks again i really appreciate your work!
